#pragma config(Motor,  port1,           LBdrive,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           Ldr4b,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Lmobgoal,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           L4bar,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LFdrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RFdrive,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Rmobgoal,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Rdr4b,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          RBdrive,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Uses code from JoystickControl_v5
//Controller 1 controls driving
//Controller 2 controls lifting mechanisms

task main()
{
	while(true)
	{

		//Drive Chain
		motor[LFdrive] = vexRT[Ch3];
	  motor[LBdrive] = vexRT[Ch3];
		motor[RFdrive] = vexRT[Ch2];
		motor[RBdrive] = vexRT[Ch2];

		if(vexRT[Btn7U] == 1)
		{
			motor[Ldr4b] = 127;
			motor[Rdr4b] = 127;
		}
		else if(vexRT[Btn7D] == 1)
		{
			motor[Ldr4b] = -127;
			motor[Rdr4b] = -127;
		}
		else if(vexRT[Btn7UXmtr2] == 1)
		{
			motor[Ldr4b] = 127;
			motor[Rdr4b] = 127;
		}
		else if(vexRT[Btn7DXmtr2] == 1)
		{
			motor[Ldr4b] = -127;
			motor[Rdr4b] = -127;
		}
		else
		{
			motor[Ldr4b] = 0;
			motor[Rdr4b] = 0;
		}


		//mobile goal

		if(vexRT[Btn8U] == 1)
		{
			motor[Lmobgoal] = 127;
			motor[Rmobgoal] = 127;
		}
		else if (vexRT[Btn8D] == 1)
		{
			motor[Lmobgoal] = -127;
			motor[Rmobgoal] = -127;
		}
		else
		{
			motor[Lmobgoal] = 15;
			motor[Rmobgoal] = 15;
		}

		// intake
		if (vexRT[Btn5U] == 1)
		{
			motor[intake] = 127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[intake] = -127;
		}
		else if (vexRT[Btn5UXmtr2] == 1)
		{
			motor[intake] = 127;
		}
		else if (vexRT[Btn5DXmtr2] == 1)
		{
			motor[intake] = -127;
		}
		else
		{
			motor[intake] = 20;

			//Option for motor intake to be 0 by default (mostly just for when testing and don't want to wear out motor)

			//motor[intake] = 0;

		}

		// 4bar
		if (vexRT[Btn6U] == 1)
		{
			motor[L4bar] = 127;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[L4bar] = -127;
		}
		else if (vexRT[Btn6UXmtr2] == 1)
		{
			motor[L4bar] = 127;
		}
		else if (vexRT[Btn6DXmtr2] == 1)
		{
			motor[L4bar] = -127;
		}
		else
		{
			motor[L4bar] = 0;
		}

	}
}
